<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Contrat;
/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{


}
