<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $nom, $prenom
     * @return Client
     */
    public function findClientByName($nom,$prenom) {

        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
            'SELECT c
        FROM AppBundle\Entity\Client c
        WHERE c.nom = :nom and c.prenom = :prenom
        ORDER BY p.price ASC'
        )->setParameters(array('nom' => $nom, 'prenom' => $prenom));;
        return $query->execute();
    }

}
